version: '3'
services:
  postgres:
    container_name: pg
    image: postgres
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PG_COLOR=always
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
